### ISSUE TITLE
AssertException: The control file '/etc/monitrc_root' is not a file

### ISSUE THREAD

**Issue by nosebeggar** [diogopms/monit-docker#31]
I'm guessing this is no longer maintained as the last Update was 2020, but I'll try anyway.

I made a simple docker-compose file:

```
---
version: "3"
services:
  monit:
    image: diogopms/monit-docker-kubernetes
    container_name: monit
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./monitrc:/etc/monitrc
    ports:
      - 2812:2812
    restart: unless-stopped
```

Yet when I run it (doesn't matter if via docker-compose or the regular command listed in the install section) it gives me:

```
monit    | cp: omitting directory '/etc/monitrc'
monit    | chown: /etc/monitrc_root: No such file or directory
monit    | AssertException: The control file '/etc/monitrc_root' is not a file
monit    |  raised in handle_options at src/monit.c:654
```

It seems the directory /etc/monitrc doesn't exist in the image?
